version: '3.4'

services:
  pagamento:
    container_name: pagamentoApi
    image: ${DOCKER_REGISTRY-}pagamento
    build:
      context: .
      dockerfile: src/Pagamento/Dockerfile
    networks:
      - services
    ports:
      - "8000:80"
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo
    container_name: noSql
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT:-mongodb}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-mongodb}
      MONGO_INITDB_ROOT_DATABASE: ${MONGO_ROOT_DB:-mongodb}
      SALES_PASSWORD: ${SALES_PASSWORD:-sales}
      WAREHOUSE_PASSWORD: ${WAREHOUSE_PASSWORD:-warehouse}
    ports:
      - "27017:27017"
    networks:
      - services  
    volumes:
      - ./src/scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_BASICAUTH_USERNAME: renatogroffe
  #     ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2019!
  #     ME_CONFIG_MONGODB_PORT: 27017
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2019!
  #   links:
  #     - mongo
  #   networks:
  #     - services

networks: 
    services:
      driver: bridge